### ISSUE TITLE
При запуске контейнеров в процессе подключения к БД возникает сообщение database system was shut down, и не загружаются структура и данные

### ISSUE THREAD

**Issue by Evgeniya-EVA** [Evgeniya-EVA/Postgres_DoesntWork#1]
## Шаги:
1.  Включить виртуализацию в биосе.
2. установить Docker Toolbox for Windows
3. добавить путь к каталогу с проектами в общие папки VirtualBox (рекомендовано для Windows 8.1)
4. запустить Docker Quickstart Terminal (рекомендовано для Windows 8.1)
5. выполнить команду затем `eval $(docker-machine env default)` (рекомендовано для Windows 8.1)
6. запустить Intellij Idea.
7. заполнить файл docker-compose.yml :

``` 
version: '3.7'
services:
  PostgreSQL:
    image: postgres:12.0-alpine
    volumes:
      - ./data:/var/lib/postgres/data
    ports:
      - '5432:5432'
    environment:
       POSTGRES_RANDOM_ROOT_PASSWORD: 'yes'
       POSTGRES_DATABSAE: app
       POSTGRES_USER: app
       POSTGRES_PASSWORD: pass123

  node-app:
    build: .
    image: node-app:1.0
    ports:
      - '9999:9999'
    volumes:
      - ./node:/var/lib/node_data 
```
8. добавить к папку проекта jar-файлы
9. создать файлы Dockerfile, app.js, package-lock.json, package.json, скопировав их содержание из репозитория с [домашним заданием](https://github.com/netology-code/aqa-homeworks/tree/master/docker), а также application.properties c содержанием:
```
spring.datasource.url=jdbc:postgres://192.168.99.100:5432/app
spring.datasource.username=app
sprind.datasource.password=pass123
```
10. выполнить команду `docker-compose up` или `docker-compose up --build`

## Ожидаемый результат
Выполняется загрузка образов, создание и запуск контейнеров. Распаковывается база данных. В корне каталога с проектом создается каталог data с информацией о структуре и данных базы данных и папка node.
 
## Фактический результат
Образы загружаются, контейнеры создаются и запускаются. 
![image](https://user-images.githubusercontent.com/58333040/73758835-2e81d980-477c-11ea-8001-6c6540520b06.png)

База данных не распаковывается, процесс зависает вплоть до ввода `ctrl+c`. Логи ниже.

Когда пытаюсь выполнить команду `docker-compose exec PostreSQL postgres`, получаю следующую ошибку:
![image](https://user-images.githubusercontent.com/58333040/73761599-1f048f80-4780-11ea-9d50-5e9ac0ab7f25.png)

## Окружение
Windows 8.1 x64
Docker Toolbox for Windows
Node JS 8.16.2-alpine
PostgreSQL 12.0-alpine
Intellij Idea CE 2019.2.3

## Логи
```
PostgreSQL_1  | The files belonging to this database system will be owned by user "postgres".
PostgreSQL_1  | This user must also own the server process.
PostgreSQL_1  |
PostgreSQL_1  | The database cluster will be initialized with locale "en_US.utf8".
PostgreSQL_1  | The default database encoding has accordingly been set to "UTF8".
PostgreSQL_1  | The default text search configuration will be set to "english".
PostgreSQL_1  |
PostgreSQL_1  | Data page checksums are disabled.
PostgreSQL_1  |
PostgreSQL_1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
PostgreSQL_1  | creating subdirectories ... ok
PostgreSQL_1  | selecting dynamic shared memory implementation ... posix
PostgreSQL_1  | selecting default max_connections ... 100
PostgreSQL_1  | selecting default shared_buffers ... 128MB
PostgreSQL_1  | selecting default time zone ... UTC
PostgreSQL_1  | creating configuration files ... ok
PostgreSQL_1  | running bootstrap script ... ok
PostgreSQL_1  | sh: locale: not found
PostgreSQL_1  | 2020-02-04 11:33:39.376 UTC [26] WARNING:  no usable system locales were found
PostgreSQL_1  | performing post-bootstrap initialization ... ok
PostgreSQL_1  | syncing data to disk ... ok
PostgreSQL_1  |
PostgreSQL_1  | initdb: warning: enabling "trust" authentication for local connections
PostgreSQL_1  | You can change this by editing pg_hba.conf or using the option -A, or
PostgreSQL_1  | --auth-local and --auth-host, the next time you run initdb.
PostgreSQL_1  |
PostgreSQL_1  | Success. You can now start the database server using:
PostgreSQL_1  |
PostgreSQL_1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
PostgreSQL_1  |
PostgreSQL_1  | waiting for server to start....2020-02-04 11:33:45.064 UTC [30] LOG:  starting PostgreSQL 12.0 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit
PostgreSQL_1  | 2020-02-04 11:33:45.078 UTC [30] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
PostgreSQL_1  | 2020-02-04 11:33:45.165 UTC [31] LOG:  database system was shut down at 2020-02-04 11:33:42 UTC
PostgreSQL_1  | 2020-02-04 11:33:45.186 UTC [30] LOG:  database system is ready to accept connections
PostgreSQL_1  |  done
PostgreSQL_1  | server started
PostgreSQL_1  | CREATE DATABASE
PostgreSQL_1  |
PostgreSQL_1  |
PostgreSQL_1  | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
PostgreSQL_1  |
PostgreSQL_1  | 2020-02-04 11:33:46.304 UTC [30] LOG:  received fast shutdown request
PostgreSQL_1  | waiting for server to shut down....2020-02-04 11:33:46.318 UTC [30] LOG:  aborting any active transactions
PostgreSQL_1  | 2020-02-04 11:33:46.340 UTC [30] LOG:  background worker "logical replication launcher" (PID 37) exited with exit code 1
PostgreSQL_1  | 2020-02-04 11:33:46.347 UTC [32] LOG:  shutting down
PostgreSQL_1  | 2020-02-04 11:33:46.409 UTC [30] LOG:  database system is shut down
PostgreSQL_1  |  done
PostgreSQL_1  | server stopped
PostgreSQL_1  |
PostgreSQL_1  | PostgreSQL init process complete; ready for start up.
PostgreSQL_1  |
PostgreSQL_1  | 2020-02-04 11:33:46.509 UTC [1] LOG:  starting PostgreSQL 12.0 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit
PostgreSQL_1  | 2020-02-04 11:33:46.520 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
PostgreSQL_1  | 2020-02-04 11:33:46.521 UTC [1] LOG:  listening on IPv6 address "::", port 5432
PostgreSQL_1  | 2020-02-04 11:33:46.548 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
PostgreSQL_1  | 2020-02-04 11:33:46.631 UTC [41] LOG:  database system was shut down at 2020-02-04 11:33:46 UTC
PostgreSQL_1  | 2020-02-04 11:33:46.658 UTC [1] LOG:  database system is ready to accept connections
```
![image](https://user-images.githubusercontent.com/58333040/73758482-b61b1880-477b-11ea-972d-2c6a443a4001.png)

![image](https://user-images.githubusercontent.com/58333040/73758537-c7fcbb80-477b-11ea-831b-38d5e475f70a.png)

![image](https://user-images.githubusercontent.com/58333040/73758581-d64ad780-477b-11ea-895e-345494c3b998.png)

## Кроме того:
1. при выполнении команды 'docker-compose ps' в терминале появляется сообщение:
![image](https://user-images.githubusercontent.com/58333040/73757323-21fc8180-477a-11ea-9fd2-4b65ec01787b.png)

2. плагин dockerа так и не установился в идею (не подключается к серверу):
![image](https://user-images.githubusercontent.com/58333040/73757892-f29a4480-477a-11ea-9dd2-731df8e6ef2e.png)

**Comment by coursar** [comment]
Внимательней надо быть, в задаче написано:

<img width="887" alt="Снимок экрана 2020-02-04 в 21 36 01" src="https://user-images.githubusercontent.com/3601892/73765445-5f6f0800-4796-11ea-88dd-0b9b299c9042.png">

А вы пишите `postgres`

**Comment by coursar** [comment]
1. Кроме того, бд нормально запустилась, вы можете это увидеть в логе:

```
PostgreSQL_1  | 2020-02-04 11:33:46.658 UTC [1] LOG:  database system is ready to accept connections
```

2. Не надо сервисы называть с большой буквы.

**Comment by coursar** [comment]
И на ваши "кроме того", как и на мои - надо заводить отдельные issue.

**Comment by ArRomanov** [comment]
Тоже немного добавлю:
1. Команда `docker-compose exec PostreSQL postgres` неправильная, постгрес в консоли запускается [иначе](https://ru.stackoverflow.com/questions/692470/%D0%9A%D0%B0%D0%BA-%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B8%D1%82%D1%8C-%D0%B4%D0%BE%D1%81%D1%82%D1%83%D0%BF-%D0%BA-postgres-%D0%BA%D0%BE%D0%BD%D1%81%D0%BE%D0%BB%D0%B8-%D0%B2-linux)
2. После запуска контейнеров командой `docker-compose up` ваш терминал всегда будет занят логами контейнера, нажимая **ctrl+c**  вы останавливаете контейнеры. Используйте команду `docker-compose up -d` для запуска в фоне и потом ваш терминал освободится и вы сможете подключаться к логам отдельного контейнера.

**Comment by Evgeniya-EVA** [comment]
Спасибо @coursar и @ArRomanov ! Исправления внесла, но, тем не менее, папка data не создается.

**Comment by coursar** [comment]
Если смотрите через IDEA, то там полезно сделать syncrhonize - IDEA не всегда сразу подхватывает изменения с диска, если не сама их сделала.

**Comment by Evgeniya-EVA** [comment]
@coursar сделала. Папки по-прежнему нет. и на диске тоже
